name: Deploy GitHub Pages

on:
  push:
    branches:
      - master  # Adjust this branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          mkdir -p docs  # GitHub Pages uses the 'docs' folder by default
          cp -r html/* docs/
          cp -r css/* docs/
          cp -r images/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
